
development: &default
  adapter: postgresql
  database: pricemeter_development
  username: pricemeter
  password: secret
  host: localhost 
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  port: 5433

test:
  <<: *default
  database: pricemeter_test


